//! Snapshot integration tests for the Bedrock tool-schema rewriter.
//!
//! Run with:
//! ```text
//! INSTA_UPDATE=always cargo test -p paigasus-helikon-providers-bedrock --test schema_rewriter
//! ```
//! or after new test additions:
//! ```text
//! cargo insta test --accept
//! ```

use paigasus_helikon_providers_bedrock::translate::schema::{rewrite_tool_schema, Ruleset};
use serde_json::json;

/// A realistic schemars-style adjacently-tagged enum schema (as generated by
/// `schemars::JsonSchema` with `#[serde(tag = "type", content = "payload")]`).
///
/// ```json
/// { "oneOf": [ VariantA, VariantB, VariantC ] }
/// ```
///
/// Each variant has an adjacently-tagged shape: `{ "type": <const>, "payload": <schema> }`.
#[test]
fn snapshot_adjacently_tagged_enum() {
    let input = json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Command",
        "oneOf": [
            {
                "type": "object",
                "required": ["type", "payload"],
                "properties": {
                    "type": {"type": "string", "const": "transfer"},
                    "payload": {
                        "type": "object",
                        "required": ["from", "to", "amount"],
                        "properties": {
                            "from": {"type": "string", "format": "uuid"},
                            "to": {"type": "string", "format": "uuid"},
                            "amount": {"type": "number", "minimum": 0}
                        }
                    }
                }
            },
            {
                "type": "object",
                "required": ["type", "payload"],
                "properties": {
                    "type": {"type": "string", "const": "deposit"},
                    "payload": {
                        "type": "object",
                        "required": ["account", "amount"],
                        "properties": {
                            "account": {"type": "string", "format": "uuid"},
                            "amount": {"type": "number", "minimum": 0}
                        }
                    }
                }
            },
            {
                "type": "object",
                "required": ["type", "payload"],
                "properties": {
                    "type": {"type": "string", "const": "withdrawal"},
                    "payload": {
                        "type": "object",
                        "required": ["account", "amount"],
                        "properties": {
                            "account": {"type": "string", "format": "uuid"},
                            "amount": {"type": "number", "minimum": 0}
                        }
                    }
                }
            }
        ]
    });

    let result = rewrite_tool_schema(&input, Ruleset::Strict);
    insta::assert_json_snapshot!(result);
}

/// A deeply-nested generic schema with `$defs`, nested `$ref`, `items`, and
/// unsupported keywords mixed in at multiple depths — representative of a
/// complex schemars-generated output.
#[test]
fn snapshot_deeply_nested_generic_schema() {
    let input = json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "https://paigasus.io/schemas/portfolio",
        "type": "object",
        "title": "Portfolio",
        "$comment": "Generated by schemars 0.8",
        "properties": {
            "owner": {"$ref": "#/$defs/User"},
            "accounts": {
                "type": "array",
                "items": {"$ref": "#/$defs/Account"}
            },
            "metadata": {
                "type": "object",
                "format": "free-form",
                "default": {},
                "properties": {
                    "tags": {
                        "type": "array",
                        "items": {"type": "string"},
                        "examples": [["savings", "isa"]]
                    },
                    "created_at": {
                        "type": "string",
                        "format": "date-time"
                    }
                }
            }
        },
        "$defs": {
            "User": {
                "type": "object",
                "properties": {
                    "id": {"type": "string", "format": "uuid"},
                    "name": {"type": "string"},
                    "contact": {"$ref": "#/$defs/Contact"}
                }
            },
            "Contact": {
                "type": "object",
                "properties": {
                    "email": {"type": "string", "format": "email"},
                    "phone": {"type": "string"}
                }
            },
            "Account": {
                "type": "object",
                "properties": {
                    "id": {"type": "string", "format": "uuid"},
                    "kind": {
                        "anyOf": [
                            {"type": "object", "properties": {"kind": {"const": "checking"}, "overdraft_limit": {"type": "number"}}},
                            {"type": "object", "properties": {"kind": {"const": "savings"}, "interest_rate": {"type": "number"}}}
                        ]
                    },
                    "transactions": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/Transaction"}
                    }
                }
            },
            "Transaction": {
                "type": "object",
                "properties": {
                    "amount": {"type": "number"},
                    "currency": {"type": "string", "default": "USD"},
                    "timestamp": {"type": "string", "format": "date-time"},
                    "notes": {"type": "string", "$comment": "optional free text"}
                }
            }
        }
    });

    let result = rewrite_tool_schema(&input, Ruleset::Strict);
    insta::assert_json_snapshot!(result);
}
